
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="css/about.css">
    <meta name="viewport" content="width=device-width, initial-sclae=1.0">


  </head>
  <body>
      <div class="about-section">
        <div class="inner-width">
          <h1>About Us</h1>
          <div class="border"></div>
          <div class="about-section-row">
            <div class="about-section-col">
              <div class="about">
                <p>
                  This Web Application provides facility to online examination world wide. It saves time as it allows number of students/candidates to give the exam at same time and display the results at the end of the test ,so there is no need to wait for the result. It is evaluated and generated by the server. Administrator has privileges to create, modify and delete the test papers and its particular questions .User can register, login and give the test with his specific id, and can see the results as well .Others can view sample papers to learn the structure of online exams. It eliminates the use of items like pen, paper,etc.The goal for the development for this project is to make a good platform to conduct the   online test. There is no difficulties in executing tests. In this software the test is conduct on full screen mode so, there is no cheating during the tests. To solve the early timer problem during online test.
                </p>
               
              </div>
            </div>
           
          </div>
        </div>
      </div>
  </body>
</html>
